### ISSUE TITLE
服务端nodemon 起不来

### ISSUE THREAD

**Issue by liwufan** [hjyssg/ShiguReader#38]
之前的 156f29d 可以运行， 升级到 fffc87c 报错
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@6.14.4
3 info using node@v14.0.0
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle ShiguReader@1.2.6~preserver: ShiguReader@1.2.6
6 info lifecycle ShiguReader@1.2.6~server: ShiguReader@1.2.6
7 verbose lifecycle ShiguReader@1.2.6~server: unsafe-perm in lifecycle true
8 verbose lifecycle ShiguReader@1.2.6~server: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/liwufan/codes/ShiguReader/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/liwufan/codes/ShiguReader/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle ShiguReader@1.2.6~server: CWD: /home/liwufan/codes/ShiguReader
10 silly lifecycle ShiguReader@1.2.6~server: Args: [ '-c', 'nodemon src/server/index.js' ]
11 silly lifecycle ShiguReader@1.2.6~server: Returned: code: 1  signal: null
12 info lifecycle ShiguReader@1.2.6~server: Failed to exec server script
13 verbose stack Error: ShiguReader@1.2.6 server: `nodemon src/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid ShiguReader@1.2.6
15 verbose cwd /home/liwufan/codes/ShiguReader
16 verbose Linux 5.5.10-arch1-1
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
18 verbose node v14.0.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error ShiguReader@1.2.6 server: `nodemon src/server/index.js`
22 error Exit status 1
23 error Failed at the ShiguReader@1.2.6 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hjyssg** [comment]
npm install 一下

**Comment by liwufan** [comment]
install 之后同样报错 

> [0] SyntaxError: Unexpected token / in JSON at position 0
[0]     at parse (<anonymous>)
[0]     at parseChannelMessages (internal/child_process/serialization.js:111:15)
[0]     at parseChannelMessages.next (<anonymous>)
[0]     at Pipe.channel.onread (internal/child_process.js:595:18)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! ShiguReader@1.2.6 server: `nodemon src/server/index.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the ShiguReader@1.2.6 server script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]

**Comment by hjyssg** [comment]
会用调试工具吗？visual studio code试试，追溯到报错的地方。
我这边没有报错

**Comment by hjyssg** [comment]
我另clone一个全新的，也没有报错

**Comment by liwufan** [comment]
我又试了几种方法
1. 照着readme clone全新安装，bash命令 npm run dev 同样报错。
2. 用vscode的调试模式跑一遍通过。
3. 之后用bash命令 npm run dev 也能运行了。

步骤1-3我又重复了测试了几遍，复现。
大概是vscode对目录做了什么改动

**Comment by liwufan** [comment]
>   "server": "nodemon --inspect src/server/index.js",

我在package.json开nodemon调试模式就能运行，关掉调试模式直接用

> nodemon src/server/index.js

就会一直报告语法错误

SyntaxError: Unexpected token / in JSON at position 0
[0]     at parse (<anonymous>)
[0]     at parseChannelMessages (internal/child_process/serialization.js:111:15)
[0]     at parseChannelMessages.next (<anonymous>)
[0]     at Pipe.channel.onread (internal/child_process.js:595:18)

**Comment by hjyssg** [comment]
会不会是你安装nodemon的问题。nodemon只是一个开发工具 https://nodemon.io/

你试一下
node src/server/index.js

**Comment by liwufan** [comment]
nodemon 运行时
```
liwufan@x220 ~/c/d/ShiguReader-dev> npm run dev

> ShiguReader@1.2.6 dev /home/liwufan/codes/debug/ShiguReader-dev
> concurrently "npm run server" "npm run client"

[0]
[0] > ShiguReader@1.2.6 server /home/liwufan/codes/debug/ShiguReader-dev
[0] > nodemon src/server/index.js
[0]
[1]
[1] > ShiguReader@1.2.6 client /home/liwufan/codes/debug/ShiguReader-dev
[1] > webpack-dev-server --mode development --devtool inline-source-map --hot
[1]
[0] [nodemon] 1.18.9
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: /home/liwufan/codes/debug/ShiguReader-dev/src/server/**/*
[0] [nodemon] starting `node src/server/index.js`
[0] undefined:1
[0] /home/liwufan/
[0] ^
[0]
[0] SyntaxError: Unexpected token / in JSON at position 0
[0]     at parse (<anonymous>)
[0]     at parseChannelMessages (internal/child_process/serialization.js:111:15)
[0]     at parseChannelMessages.next (<anonymous>)
[0]     at Pipe.channel.onread (internal/child_process.js:595:18)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! ShiguReader@1.2.6 server: `nodemon src/server/index.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the ShiguReader@1.2.6 server script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/liwufan/.npm/_logs/2020-05-05T04_47_51_261Z-debug.log
[0] npm run server exited with code 1
[1] clean-webpack-plugin: /home/liwufan/codes/debug/ShiguReader-dev/dist has been removed.
[1] ℹ ｢wds｣: Project is running at http://0.0.0.0:3000/
[1] ℹ ｢wds｣: webpack output is served from /
[1] ℹ ｢wds｣: 404s will fallback to /index.html
[1] Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
[1] ℹ ｢wdm｣: Hash: ccd19f38da60eeb3f603
[1] Version: webpack 4.29.0
[1] Time: 8063ms
[1] Built at: 2020/05/05 下午12:47:59
[1]             Asset       Size  Chunks             Chunk Names
[1]         bundle.js   9.96 MiB    main  [emitted]  main
[1] favicon-96x96.png   15.4 KiB          [emitted]
[1]        index.html  560 bytes          [emitted]
[1] Entrypoint main = bundle.js
[1] [0] multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js babel-polyfill ./src/client/index.js 64 bytes {main} [built]
[1] [./node_modules/babel-polyfill/lib/index.js] 833 bytes {main} [built]
[1] [./node_modules/core-js/fn/regexp/escape.js] 108 bytes {main} [built]
[1] [./node_modules/core-js/shim.js] 8.03 KiB {main} [built]
[1] [./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[1] [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[1] [./node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
[1] [./node_modules/react/index.js] 190 bytes {main} [built]
[1] [./node_modules/regenerator-runtime/runtime.js] 23.9 KiB {main} [built]
[1] [./node_modules/url/url.js] 22.8 KiB {main} [built]
[1] [./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:3000] (webpack)-dev-server/client?http://0.0.0.0:3000 7.78 KiB {main} [built]
[1] [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[1] [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[1] [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {main} [built]
[1] [./src/client/index.js] 295 bytes {main} [built]
[1]     + 897 hidden modules
[1] Child html-webpack-plugin for "index.html":
[1]      1 asset
[1]     Entrypoint undefined = index.html
[1]     [./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html] 661 bytes {0} [built]
[1]     [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
[1]     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
[1]     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[1] ℹ ｢wdm｣: Compiled successfully.
^C[1] npm run client exited with code SIGINT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ShiguReader@1.2.6 dev: `concurrently "npm run server" "npm run client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ShiguReader@1.2.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liwufan/.npm/_logs/2020-05-05T04_48_01_686Z-debug.log
```

**Comment by liwufan** [comment]
node src/server/index.js
```
liwufan@x220 ~/c/d/ShiguReader-dev [1]> node src/server/index.js
--------------------
process.cwd() /home/liwufan/codes/debug/ShiguReader-dev
__filename /home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js
__dirname /home/liwufan/codes/debug/ShiguReader-dev/src/server
rootPath /home/liwufan/codes/debug/ShiguReader-dev
log path: /home/liwufan/codes/debug/ShiguReader-dev/workspace/log/2020-05-05-12-05.log
path_will_scan:
----------------------
scanning local files
[file-iterator] T:\迅雷下载 does not exist! Please check you path-config and user-config.js
[file-iterator] T:\迅雷下载 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_Happy_Lesson does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_Happy_Lesson\_Unread does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson\_Unread 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort 不存在! 检查一下你的path-config和user-config.js
[file-iterator] E:\_Temp_Music does not exist! Please check you path-config and user-config.js
[file-iterator] E:\_Temp_Music 不存在! 检查一下你的path-config和user-config.js
[file-iterator] E:\_temp_comic does not exist! Please check you path-config and user-config.js
[file-iterator] E:\_temp_comic 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_AV does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_AV 不存在! 检查一下你的path-config和user-config.js
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-colord.service-py2fAi'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-colord.service-py2fAi'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-logind.service-IRfBIi'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-logind.service-IRfBIi'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-timesyncd.service-sQbrEf'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-timesyncd.service-sQbrEf'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-vnstat.service-nOoOVf'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/debug/ShiguReader-dev/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-vnstat.service-nOoOVf'
}
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_good\good_2020_05_01 does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_good\good_2020_05_01 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_good does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_good 不存在! 检查一下你的path-config和user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_Compressed_2020 does not exist! Please check you path-config and user-config.js
[file-iterator] D:\_Happy_Lesson\_Going_to_sort\_Compressed_2020 不存在! 检查一下你的path-config和user-config.js
0.008s  to read local dirs
Analyzing local files
There are 8 files
----------scan cache------------
[file-iterator] /home/liwufan/codes/debug/ShiguReader-dev/cache does not exist! Please check you path-config and user-config.js
[file-iterator] /home/liwufan/codes/debug/ShiguReader-dev/cache 不存在! 检查一下你的path-config和user-config.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1314:16)
    at listenInCluster (net.js:1362:12)
    at Server.listen (net.js:1448:7)
    at Function.listen (/home/liwufan/codes/debug/ShiguReader-dev/node_modules/express/lib/application.js:618:24)
    at init (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:219:24)
    at Object.<anonymous> (/home/liwufan/codes/debug/ShiguReader-dev/src/server/index.js:1099:1)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1341:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8080
}
```

**Comment by hjyssg** [comment]
昨天我把user config改了，拆出path config要改。你改一下path-config。
然后端口是改port-config

**Comment by liwufan** [comment]
```
liwufan@x220 ~/c/ShiguReader (myconf)> node src/server/index.js
--------------------
process.cwd() /home/liwufan/codes/ShiguReader
__filename /home/liwufan/codes/ShiguReader/src/server/index.js
__dirname /home/liwufan/codes/ShiguReader/src/server
rootPath /home/liwufan/codes/ShiguReader
log path: /home/liwufan/codes/ShiguReader/workspace/log/2020-05-05-01-05.log
path_will_scan:
----------------------
scanning local files
[file-iterator] scan: 0
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-colord.service-py2fAi'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/ShiguReader/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/ShiguReader/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-colord.service-py2fAi'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-logind.service-IRfBIi'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/ShiguReader/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/ShiguReader/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-logind.service-IRfBIi'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-timesyncd.service-sQbrEf'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/ShiguReader/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/ShiguReader/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-systemd-timesyncd.service-sQbrEf'
}
[file-iterator] Error: EACCES: permission denied, scandir '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-vnstat.service-nOoOVf'
    at Object.readdirSync (fs.js:974:3)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:16)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:66:17
    at Array.forEach (<anonymous>)
    at iterate (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:64:31)
    at /home/liwufan/codes/ShiguReader/src/server/file-iterator.js:18:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/liwufan/codes/ShiguReader/src/server/file-iterator.js:12:13)
    at init (/home/liwufan/codes/ShiguReader/src/server/index.js:177:21)
    at Object.<anonymous> (/home/liwufan/codes/ShiguReader/src/server/index.js:1099:1) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/tmp/systemd-private-ea5bf2d67a29427791caf2695205beb0-vnstat.service-nOoOVf'
}
0.032s  to read local dirs
Analyzing local files
There are 677 files
----------scan cache------------
[file-iterator] scan: 0
[file-iterator] scan: 2000
[file-iterator] scan: 4000
[file-iterator] scan: 6000
----------------------------------------------------------------
Express Server listening on port 8081
```

**Comment by liwufan** [comment]
改完设置的nodemon之前发过了

> install 之后同样报错
> 
> > [0] SyntaxError: Unexpected token / in JSON at position 0
> > [0]     at parse ()
> > [0]     at parseChannelMessages (internal/child_process/serialization.js:111:15)
> > [0]     at parseChannelMessages.next ()
> > [0]     at Pipe.channel.onread (internal/child_process.js:595:18)
> > [0] npm ERR! code ELIFECYCLE
> > [0] npm ERR! errno 1
> > [0] npm ERR! ShiguReader@1.2.6 server: `nodemon src/server/index.js`
> > [0] npm ERR! Exit status 1
> > [0] npm ERR!
> > [0] npm ERR! Failed at the ShiguReader@1.2.6 server script.
> > [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > [0]

**Comment by hjyssg** [comment]
server/index.js 的
```
const path_config_path = path.join(rootPath, "src", "path-config");
let home_pathes = fs.readFileSync(path_config_path).toString().split('\n');
home_pathes = home_pathes
               .map(e => e.trim().replace(/\n|\r/g, ""))
               .filter(pp =>{ return pp && pp.length > 0 && !pp.startsWith("#");});
const getDownloadsFolder = require('downloads-folder');
home_pathes.push(getDownloadsFolder());
const path_will_scan = home_pathes.concat(userConfig.good_folder, userConfig.good_folder_root, userConfig.not_good_folder);
```

添加了系统download文件夹，可能是linux的权限问题，扫描了不行？
你把

const getDownloadsFolder = require('downloads-folder');
home_pathes.push(getDownloadsFolder());

删了试试。

**Comment by liwufan** [comment]
删除这两行后  npm run dev 可以正常运行了

**Comment by hjyssg** [comment]
帮我提个pr修一下吧。我没linux，没法测
加这个是为了那些windows小白path都不会设，打开至少有个download文件夹

**Comment by liwufan** [comment]
我研究一下
